#Ansible docker-compose is written based on this file.


version: "2"
services:
  stockapp:
#    image: sungmindocker/skeleton:stockapp_v1
    build: .
    env_file: .env
    command: python3 app.py
    ports:
      - "5000:5000"
    volumes:
      - ./app:/home/app
      - ./files:/home/app/mounted_data
    depends_on:
      - db
  db:
    image: postgres:14
    env_file: .env
#    expose:
#      - 5432
    ports:
      - "5432:5432"



#    volumes:
#      - pgdata:/var/lib/postgresql/files
#volumes:
#  pgdata: {}
