#Ansible docker-compose is written based on this file.
# Using this file to test on your local machine / cloud server(ec2).

version: "2"
services:
  stockapp:
    image: sungmindocker/skeleton:stockapp_v1_3_amd64
#    build: .
    env_file: .env
#    command: python3 app.py
    command: "python3 app.py \
                      --target_company AAPL \
                      --date_from 2020-01-01 \
                      --date_to 2021-0101"
    ports:
      - "5000:5000"
    volumes:
      - ./app:/home/app
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    ports:
      - "5432:5432"