---

# How to run this playbook
# $ansible-playbook create-db-table-playbook.yml -i inventory.yml --vault-password-file .vaultpass

- hosts: aws

  become: yes
  become_method: sudo
  remote_user: ubuntu
  gather_facts: no

  vars_files:
    - vault.yml
  vars:
    sub_playbooks_dir: "{{ playbook_dir }}/tasks"
    stock_app_dir: /var/local/stockapp
    ec2_mounted_data_dir: /var/local/stockapp/app/data
    git_repo: https://github.com/sungmin-yang/ansible-aws-docker-app.git

    # Args for app server (a docker container)
    target_company: AAPL
    date_from: 2021-01-01
    date_to: 2022-01-14
    subset_num: 100
    stock_table_name: stocks
    million_table_name: random1m


  tasks:
    - import_tasks: "{{ sub_playbooks_dir }}/install-requirements-playbook.yml"
    - import_tasks: "{{ sub_playbooks_dir }}/git-repo-playbook.yml"
    - import_tasks: "{{ sub_playbooks_dir }}/docker-run-playbook.yml"
    - import_tasks: "{{ sub_playbooks_dir }}/generate-sample-db-playbook.yml"
    - import_tasks: "{{ sub_playbooks_dir }}/retrieve_subset-1m-playbook.yml"
    - import_tasks: "{{ sub_playbooks_dir }}/store-gathered-data-to-ansible.yml"

#    Shutting down docker containers.
#    - import_tasks: "{{ sub_playbooks_dir }}/docker-down-playbook.yml"
