---
#- name: Run instances with docker compose up
- docker_compose:
    project_src: app
    state: absent

- docker_compose:
    project_name: stockapp
    definition:
      version: '2'
      services:
        web:
          image: sungmindocker/skeleton:stockapp_v1
          env_file: "{{ playbook_dir }}/.env"
          #              build: "{{ playbook_dir }}/app"
          #              command: "python manage.py runserver 0.0.0.0:8000"
          volumes:
#                - "{{ playbook_dir }}/flask:/code"
            - "{{ playbook_dir }}/app:/home/app/"
            - "{{ playbook_dir }}/app/files:/home/app/files"
          ports:
            - "5000:5000"
          depends_on:
            - db
        db:
          image: postgres:10
          env_file: "{{ playbook_dir }}/.env"
          expose:
            - 5432
  register: output

- debug:
    var: output
- assert:
    that:
      - "output.services.web.stockapp_web_1.state.running"
      - "output.services.db.stockapp_db_1.state.running"


#    - name: Get infos on container
#      docker_container_info:
#        name: stockapp_web_1
#      register: result
#
#    - name: Print information about container
#      debug:
#        var: result.container

