---
- name: Docker compose up for app and db server
  block:

  - name: Ensure there are no same docker conatiners are running.
    docker_compose:
      project_src: "{{ stock_app_dir }}"
      state: absent

  - name: Running app and db server with docker-compose up
    # Written based on docker-compose.yml file.
    docker_compose:
      project_name: stockapp
      definition:
        version: '2'
        services:
          web:
            image: sungmindocker/skeleton:stockapp_v1_3_amd64
            env_file: "{{ stock_app_dir }}/.env"
            command: "python3 app.py \
                      --target_company {{ target_company }} \
                      --date_from {{ date_from }} \
                      --date_to {{ date_to }}"

            volumes:
              - "{{ stock_app_dir }}/app:/home/app/"
              - "{{ ec2_mounted_data_dir }}:/home/app/data"
            ports:
              - "5000:5000"
            depends_on:
              - db
          db:
            image: postgres:10
            env_file: "{{ stock_app_dir }}/.env"
            ports:
              - "5432:5432"
    register: output

  - debug:
      var: output

  - assert:
      that:
        - "output.services.web.stockapp_web_1.state.running"
        - "output.services.db.stockapp_db_1.state.running"
#
#      - "output.services.db.stockapp_db_1.state.running"
#      - "output.services.stockapp.stockapp_stockapp_1.state.running"


#    - name: Get infos on container
#      docker_container_info:
#        name: stockapp_web_1
#      register: result
#
#    - name: Print information about container
#      debug:
#        var: result.container

