---
- name: Retrieve subset 100 through App server
  command: "python3 retrieve_subset.py \
          --user {{POSTGRES_USER}} \
          --password {{POSTGRES_PASSWORD}} \
          --db {{POSTGRES_DB}} \
          --host {{ POSTGRES_LOCAL_HOST }} \
          --tablename {{ million_table_name }} \
          --rownumber {{ subset_num }} \
          --filename ./data/subset100_from_1M.csv"
  timeout: 30
  args:
    chdir: "{{ stock_app_dir }}/app"
  register: "out"

- name: Show test output
  debug:
    msg: "{{ out }}"

#- name: Store gathered data on ansible server file /tmp/subset100_from_1M.csv
#  fetch:
#    src: "{{ ec2_mounted_data_dir }}/generated1m.csv"
#    dest: /tmp/gathered_data.csv
#    flat: yes