---
- name: Retrieve subset 100 from App server
  command: "python3 retrieve_subset.py \
          --user {{POSTGRES_USER}} \
          --password {{POSTGRES_PASSWORD}} \
          --db {{POSTGRES_DB}} \
          --host {{ POSTGRES_LOCAL_HOST }} \
          --rownumber {{ subset_num }}"
#              --filename ./files/generated3.csv
  timeout: 30
  args:
    chdir: "{{ stock_app_dir }}/app"
  register: "out"

- name: Show test output
  debug:
    msg: "{{ out }}"

- name: Store gathered data on ansible server file /tmp/gathered_data.csv
  fetch:
    src: "{{ stock_app_dir }}/app/data/gathered_data.csv"
    dest: /tmp/gathered_data.csv
    flat: yes