---
all:
  hosts:
    127.0.0.1:
       ansible_connection: local
       ansible_python_interpreter: /Users/sungmin/.pyenv/versions/3.8.6/bin/python
# /home/sudheer/workspace/pvenvs/ansibleenv/bin/python is the python virtualenv where docker-py is installed
# docker-py==1.10.6