# PostgreSQL ping dbsrv server from the shell:
# ansible dbsrv -m postgresql_ping
---
- hosts: localhost
# In the example below you need to generate certificates previously.
# See https://www.postgresql.org/docs/current/libpq-ssl.html for more information.
- name: PostgreSQL ping dbsrv server using not default credentials and ssl
  community.postgresql.postgresql_ping:
    db: testdb
    login_host: db
    login_user: admin
    login_password: password
#    ca_cert: /root/root.crt
    ssl_mode: disable